<?xml version="1.0" encoding="utf-8"?><Database Name="ExamenMariaCervera" Class="InventarioDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=ExamenMariaCervera;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ExamenMariaCerveraConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Inventory" Member="Inventory">
    <Type Name="Inventory">
      <Column Name="DealName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LocalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Titles" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AvailableSince" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>